os: osx
osx_image: xcode10.1	
language: swift
env:
  - XCODE_SCHEME=VKarmaneSDK-Example
    XCODE_WORKSPACE=Example/VKarmaneSDK.xcworkspace
    XCODE_DESTINATION="platform=iOS Simulator,OS=10.0,name=iPhone 5s"
script:
  - xcodebuild clean -workspace "$XCODE_WORKSPACE" -scheme "$XCODE_SCHEME"
  - set -o pipefail && xcodebuild build -workspace "$XCODE_WORKSPACE" -scheme "$XCODE_SCHEME" -destination "$XCODE_DESTINATION" | xcpretty -s
  - pod lib lint
